version: "3.8"
services:
  stats-server:
    image: stats-server
    build: stats-service/stats-server
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: iamroot
      SPRING_PROFILES_ACTIVE: prod

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
      POSTGRES_DB: postgres

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      STATS_SERVER_URL: http://stats-server:9090
      SPRING_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: iamroot

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
      POSTGRES_DB: ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
#
#    volumes:
#      - ./ewm-service/src/main/resources:/docker-entrypoint-initdb.d/schema.sql